# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='photo_path',
        ),
    ]
